### server port
server:
  port: 8082
  servlet:
    context-path: /

## logging
logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

## keycloak
spring:
  main:
    allow-circular-references: true

## External API
externalAPI:
  url:
    base: https://testapi.cgo.cl
    validateUser: /users/validate

## SAML
saml:
  keystore:
    path: classpath:/saml/keystore.jks
    password: 123456
    alias: spring_client
  url:
    idp: http://localhost:8081
  session:
    maxSessionTimeoutInMinutes: 5
